COLORS = {
    "BLACK": 0,
    "GREY_LO": 1,
    "GREY_MD": 2,
    "WHITE": 3,
    "ROSE": 4,
    "RED_HI": 5,
    "RED": 6,
    "RED_LO": 7,
    "RED_AMBER": 8,
    "AMBER_HI": 9,
    "AMBER": 10,
    "AMBER_LO": 11,
    "AMBER_YELLOW": 12,
    "YELLOW_HI": 13,
    "YELLOW": 14,
    "YELLOW_LO": 15,
    "YELLOW_LIME": 16,
    "LIME_HI": 17,
    "LIME": 18,
    "LIME_LO": 19,
    "LIME_GREEN": 20,
    "GREEN_HI": 21,
    "GREEN": 22,
    "GREEN_LO": 23,
    "GREEN_SPRING": 24,
    "SPRING_HI": 25,
    "SPRING": 26,
    "SPRING_LO": 27,
    "SPRING_TURQUOISE": 28,
    "TURQUOISE_LO": 29,
    "TURQUOISE": 30,
    "TURQUOISE_HI": 31,
    "TURQUOISE_CYAN": 32,
    "CYAN_HI": 33,
    "CYAN": 34,
    "CYAN_LO": 35,
    "CYAN_SKY": 36,
    "SKY_HI": 37,
    "SKY": 38,
    "SKY_LO": 39,
    "SKY_OCEAN": 40,
    "OCEAN_HI": 41,
    "OCEAN": 42,
    "OCEAN_LO": 43,
    "OCEAN_BLUE": 44,
    "BLUE_HI": 45,
    "BLUE": 46,
    "BLUE_LO": 47,
    "BLUE_ORCHID": 48,
    "ORCHID_HI": 49,
    "ORCHID": 50,
    "ORCHID_LO": 51,
    "ORCHID_MAGENTA": 52,
    "MAGENTA_HI": 53,
    "MAGENTA": 54,
    "MAGENTA_LO": 55,
    "MAGENTA_PINK": 56,
    "PINK_HI": 57,
    "PINK": 58,
    "PINK_LO": 59,
}

by_number = dict()

for color in COLORS:
    globals()[color] = COLORS[color]
    by_number[COLORS[color]] = color
