#!/bin/perl -w
use strict;
chdir "/home/patch/Musical-Instrument/" or die $!;

# mod-host runs lv2 plugins
my $MOD_HOST='/home/patch/mod-host/bin/mod-host';
-e $MOD_HOST or die $!;

# Check if mod-host is running
my @psx = `ps x`;
my  $mod_host_running = grep{/mod-host/} @psx;
if(!$mod_host_running){
    # Need to start mod-host
    my $p = fork();

    if($p == 0) {
	# Child
	`$MOD_HOST`;
	exit;
    }
}

# Check if jack running
my $res =`jack_wait -c 2>/dev/null`;
chomp $res;
$res eq "running" or die "Jack is not running\n";

# Check griode is running
my $pid_file = ".griode.pid";
my $running = 0;
if(-e  $pid_file){
    my $pid = `cat .griode.pid`;
    $running = grep{/^$pid\s/} `ps x`;
}

if(!$running){
    my $griode_cmd = 'LOG_LEVEL=INFO GRIODE_AUDIO_DRIVER=jack' .
	'  ./griode.py 2>&1 |tee /tmp/griode.log';
    my $pid = fork();
    defined($pid) or die "$!: Cannot fork";
    if($pid == 0){
	# Child
	exec "$griode_cmd" or die "$!: Could not exec";
    }
}

wait;

# Clean up
#unlink($cmdPipe);


